---
modules:
  - type: dnf
    install:
      packages:
        - alacritty
        - emacs
        - vim
        - neovim
        - zathura
        - zathura-cb
        - zathura-ps
        - zathura-djvu
        - zathura-pdf-poppler
  - default-flatpaks:
      configurations:
        - notify: true
          install:
            - io.gitlab.librewolf-community
            - org.libreoffice.LibreOffice
            - dev.vencord.Vesktop
            - org.localsend.localsend_app
  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - GeistMono
        - CommitMono
        - GohuFont
        - ProggyClean
        - Terminus
        - DepartureMono
        - NerdFontsSymbolsOnly
  - type: signing
